### ISSUE TITLE
Cannot run Ganspace -- RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by 6630507** [harskish/ganspace#6] opened 2020-04-25 15:53 UTC
I am very interested in this software, however, I am having difficulty getting interactive.py to run properly.

I am running Linux / Ubuntu 18.04 on an 8-core Intel Xeon E5462 tower with an NVIDIA GTX 1070 GPU, compute level 6.1.  I installed all dependencies and built pycuda with opengl support; cuda 10.1 is available both on my system and in my anaconda environment.

On executing "python interactive.py --model=StyleGAN2 --class=ffhq --layer=style --use_w -n=1000000 -b=10000" I get the following error:

```
Traceback (most recent call last):
  File "interactive.py", line 644, in <module>
    setup_model()
  File "interactive.py", line 143, in setup_model
    inst = get_instrumented_model(model_name, class_name, layer_name, torch.device('cuda'), use_w=args.use_w)
  File "/mnt/drive2/pytorch/ganspace/models/wrappers.py", line 699, in get_instrumented_model
    latent_shape = model.get_latent_shape()
  File "/mnt/drive2/pytorch/ganspace/netdissect/modelconfig.py", line 107, in create_instrumented_model
    latent_shape=getattr(args, 'latent_shape', None))
  File "/mnt/drive2/pytorch/ganspace/netdissect/modelconfig.py", line 137, in annotate_model_shapes
    output = model(dry_run)
  File "/home/my-user/anaconda3/envs/ganspace/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/drive2/pytorch/ganspace/netdissect/nethook.py", line 48, in forward
    return self.model(*inputs, **kwargs)
  File "/home/my-user/anaconda3/envs/ganspace/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/drive2/pytorch/ganspace/models/wrappers.py", line 189, in forward
    truncation=self.truncation, truncation_latent=self.latent_avg, input_is_w=self.w_primary)
  File "/home/my-user/anaconda3/envs/ganspace/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/drive2/pytorch/ganspace/models/stylegan2/stylegan2-pytorch/model.py", line 495, in forward
    styles = [self.style(s) for s in styles]
  File "/mnt/drive2/pytorch/ganspace/models/stylegan2/stylegan2-pytorch/model.py", line 495, in <listcomp>
    styles = [self.style(s) for s in styles]
  File "/home/my-user/anaconda3/envs/ganspace/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/drive2/pytorch/ganspace/netdissect/nethook.py", line 181, in new_forward
    original_x = original_forward(*inputs, **kwargs)
  File "/home/my-user/anaconda3/envs/ganspace/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/my-user/anaconda3/envs/ganspace/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/drive2/pytorch/ganspace/models/stylegan2/stylegan2-pytorch/model.py", line 153, in forward
    out = F.linear(input, self.weight * self.scale)
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)
```

Any help would be greatly appreciated.

**Comment by harskish** [comment] 2020-04-27 08:30
It looks like the error is raised from within PyTorch when executing F.linear(). This looks like an issue with PyTorch itself, probably caused by a broken environment.

Are you able to run visualize.py or interactive.py for other models, such as BigGAN and StyleGAN1? Could you also check that F.linear() works on the cuda device in the python interpreter?

**Comment by harskish** [comment] 2020-05-05 08:11
Closing since this doesn't look like a GANSpace issue. Feel free to reopen if you find evidence that indicates otherwise.

**Closed as completed by harskish** 2020-05-05 08:11 UTC
